"""Generate the UI preset projection from the Python domain registry.

The Python domain registry remains the only editable source for transcription
defaults and model calibration. The generated TypeScript file is a build-time
projection for the React parameter editor; it is never edited by hand.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from whisper_subtitle.domain.presets import (  # noqa: E402
    MODEL_CALIBRATED_IDS,
    PRESETS,
    derive_preset,
)
from whisper_subtitle.domain.models import SUPPORTED_MODEL_IDS  # noqa: E402
from whisper_subtitle.domain.parameters import (  # noqa: E402
    PARAMETER_RULES, SPECIAL_PARAMETERS, NULLABLE_PARAMETERS, TEXT_PARAMETERS,
    ENGINE_DEFAULTS, VAD_PARAMETER_NAMES, parameter_schema,
)


OUTPUT_PATH = PROJECT_ROOT / "apps" / "web" / "src" / "data" / "presetCatalog.generated.ts"
MODEL_IDS = tuple(SUPPORTED_MODEL_IDS)
UI_PARAMETER_KEYS = tuple(PARAMETER_RULES) + tuple(sorted(SPECIAL_PARAMETERS))
SCHEMA_PATH = PROJECT_ROOT / "contracts/desktop_ipc/v1/desktop_ipc.schema.json"


def ui_parameters(preset: Any, model_id: str) -> dict[str, Any]:
    effective = derive_preset(preset.id, {}, model_id=model_id).transcription_options()
    values = dict(ENGINE_DEFAULTS)
    values.update({key: value for key, value in effective.items() if key in UI_PARAMETER_KEYS})
    for key, vad_name in VAD_PARAMETER_NAMES.items():
        if vad_name in effective["vad_parameters"]:
            values[key] = effective["vad_parameters"][vad_name]
    return {key: values[key] for key in UI_PARAMETER_KEYS}


def parameter_typescript() -> str:
    lines = ["export interface EditableParameters {"]
    for key in UI_PARAMETER_KEYS:
        if key == "task":
            kind = "'transcribe' | 'translate'"
        elif key == "temperature":
            kind = "number | number[]"
        elif key == "suppress_tokens":
            kind = "number[]"
        elif key in TEXT_PARAMETERS or key == "language":
            kind = "string"
        else:
            kind = "boolean" if PARAMETER_RULES[key][0] is bool else "number"
        if key in NULLABLE_PARAMETERS:
            kind += " | null"
        lines.append(f"  {key}: {kind};")
    lines.append("}")
    return "\n".join(lines)


def build_catalog() -> tuple[dict[str, dict[str, dict[str, Any]]], dict[str, Any]]:
    parameters: dict[str, dict[str, dict[str, Any]]] = {}
    for preset in PRESETS:
        parameters[preset.id] = {
            model_id: ui_parameters(preset, model_id) for model_id in MODEL_IDS
        }

    profiles: dict[str, Any] = {}
    for model_id in MODEL_IDS:
        if model_id not in MODEL_CALIBRATED_IDS:
            profiles[model_id] = {"temperatureFallbackMax": None}
            continue
        sample = derive_preset(PRESETS[0].id, {}, model_id=model_id).transcription_options()
        profiles[model_id] = {
            "temperatureFallbackMax": max(sample["temperature"]),
        }
    return parameters, profiles


def render() -> str:
    parameters, profiles = build_catalog()
    parameter_json = json.dumps(parameters, ensure_ascii=False, indent=2)
    profile_json = json.dumps(profiles, ensure_ascii=False, indent=2)
    source = (
        "/* This file is generated by tools/codegen/generate_preset_catalog.py. */\n"
        "/* Edit domain/presets.py or domain/parameters.py instead. */\n\n"
        "import type { ModelId, PresetId } from '../contracts/desktop';\n\n"
        + parameter_typescript() + "\n\n"
        + "export const PARAMETER_SCHEMA = " + json.dumps(parameter_schema(), ensure_ascii=False)
        + " as const;\n\n"
        +
        "export const GENERATED_PRESET_PARAMETERS = "
        f"{parameter_json} as const satisfies Record<PresetId, Record<ModelId, EditableParameters>>;\n\n"
        "export const GENERATED_MODEL_PROFILES = "
        f"{profile_json} as const satisfies Record<\n"
        "  ModelId,\n"
        "  { temperatureFallbackMax: number | null }\n"
        ">;\n"
    )
    corepack = shutil.which("corepack") or shutil.which("corepack.cmd")
    if corepack is None:
        raise RuntimeError("corepack is required to format the generated TypeScript catalog")
    formatted = subprocess.run(
        [corepack, "pnpm", "exec", "prettier", "--parser", "typescript"],
        cwd=PROJECT_ROOT,
        input=source,
        capture_output=True,
        check=True,
        text=True,
        encoding="utf-8",
    )
    return formatted.stdout


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the generated file is stale")
    args = parser.parse_args()
    expected = render()
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    generated_schema = parameter_schema()
    if args.check and schema["$defs"]["ParameterOverrides"] != generated_schema:
        print("stale generated ParameterOverrides IPC schema", file=sys.stderr)
        return 1
    if not args.check:
        # Replace just this definition to preserve formatting of the rest of v1.
        raw = SCHEMA_PATH.read_text(encoding="utf-8")
        begin = raw.index('    "ParameterOverrides": {')
        decoder = json.JSONDecoder()
        start = raw.index('{', begin)
        _, length = decoder.raw_decode(raw[start:])
        replacement = json.dumps(generated_schema, ensure_ascii=False, indent=2).replace("\n", "\n    ")
        SCHEMA_PATH.write_text(raw[:start] + replacement + raw[start + length:], encoding="utf-8", newline="\n")
    current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else None
    if args.check:
        if current != expected:
            print(f"stale generated preset catalog: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8", newline="\n")
    print(f"generated {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
