#!/usr/bin/env python3
"""Generate Rust and TypeScript projections of the Python model catalog."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any, Iterable


PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from whisper_subtitle.domain.models import (  # noqa: E402
    CALIBRATED_MODEL_IDS,
    DEFAULT_MODEL_ID,
    MODEL_DEFINITIONS,
    SECONDARY_RECOGNITION_MODEL_IDS,
    SUPPORTED_MODEL_IDS,
    TRANSLATION_MODEL_IDS,
    MODEL_ASSETS,
)
from whisper_subtitle.domain.backend_parameters import QWEN_PARAMETER_NAMES, QWEN_LANGUAGES


TYPESCRIPT_OUTPUT = (
    PROJECT_ROOT / "apps" / "web" / "src" / "contracts" / "modelCatalog.generated.ts"
)
RUST_OUTPUT = (
    PROJECT_ROOT
    / "apps"
    / "desktop"
    / "src-tauri"
    / "src"
    / "worker_host"
    / "model_catalog.rs"
)
SCHEMA_PATH = (
    PROJECT_ROOT / "contracts" / "desktop_ipc" / "v1" / "desktop_ipc.schema.json"
)


def _ordered(values: Iterable[str]) -> tuple[str, ...]:
    selected = set(values)
    return tuple(model_id for model_id in SUPPORTED_MODEL_IDS if model_id in selected)


def _typescript_array(name: str, values: Iterable[str]) -> str:
    items = "\n".join(f"  {json.dumps(value)}," for value in values)
    return f"export const {name} = [\n{items}\n] as const;"


def render_typescript() -> str:
    source = "\n\n".join(
        (
            "/* This file is generated by tools/codegen/generate_model_catalog.py. */\n"
            "/* Edit src/whisper_subtitle/domain/models.py instead. */",
            _typescript_array("MODEL_IDS", SUPPORTED_MODEL_IDS),
            f"export const DEFAULT_MODEL_ID = {json.dumps(DEFAULT_MODEL_ID)} as const;",
            _typescript_array("CALIBRATED_MODEL_IDS", _ordered(CALIBRATED_MODEL_IDS)),
            _typescript_array(
                "SECONDARY_RECOGNITION_MODEL_IDS",
                _ordered(SECONDARY_RECOGNITION_MODEL_IDS),
            ),
            _typescript_array("TRANSLATION_MODEL_IDS", _ordered(TRANSLATION_MODEL_IDS)),
            "export const MODEL_CAPABILITIES = " + json.dumps({
                model.id: {"label": model.label, "backend": model.backend,
                           "parameters": sorted(QWEN_PARAMETER_NAMES) if model.backend == "qwen3-asr" else None,
                           "languages": list(QWEN_LANGUAGES) if model.backend == "qwen3-asr" else None,
                           "companionId": model.companion_id}
                for model in MODEL_DEFINITIONS
            }, ensure_ascii=False, indent=2) + " as const;",
        )
    ) + "\n"
    corepack = shutil.which("corepack") or shutil.which("corepack.cmd")
    if corepack is None:
        raise RuntimeError("corepack is required to format the generated TypeScript catalog")
    formatted = subprocess.run(
        [corepack, "pnpm", "exec", "prettier", "--parser", "typescript"],
        cwd=PROJECT_ROOT,
        input=source,
        capture_output=True,
        check=True,
        text=True, encoding="utf-8",
    )
    return formatted.stdout


def _rust_array(name: str, values: Iterable[str]) -> str:
    values = tuple(values)
    inline_items = ", ".join(f'"{value}"' for value in values)
    inline = f"pub(super) const {name}: &[&str] = &[{inline_items}];"
    if len(inline) <= 100:
        return inline
    items = "\n".join(f'    "{value}",' for value in values)
    return f"pub(super) const {name}: &[&str] = &[\n{items}\n];"


def _rust_repository(repository: str) -> str:
    return "models--" + repository.replace("/", "--")


def render_rust() -> str:
    entries = []
    for model in MODEL_DEFINITIONS:
        repositories = tuple(_rust_repository(value) for value in model.repositories)
        if len(repositories) == 1:
            inline = f'    ("{model.id}", "{model.label}", &["{repositories[0]}"]),'
            entries.append(
                inline
                if len(inline) <= 67
                else "\n".join(
                    (
                        "    (",
                        f'        "{model.id}",',
                        f'        "{model.label}",',
                        f'        &["{repositories[0]}"],',
                        "    ),",
                    )
                )
            )
        else:
            repository_lines = "\n".join(f'            "{value}",' for value in repositories)
            entries.append(
                "\n".join(
                    (
                        "    (",
                        f'        "{model.id}",',
                        f'        "{model.label}",',
                        "        &[",
                        repository_lines,
                        "        ],",
                        "    ),",
                    )
                )
            )
    assets = []
    for model in MODEL_ASSETS:
        files = ", ".join(json.dumps(name) for name in model.required_files)
        repositories = ", ".join(json.dumps(_rust_repository(name)) for name in model.repositories)
        config_type = f'Some("{model.config_model_type}")' if model.config_model_type else "None"
        architecture = f'Some("{model.config_architecture}")' if model.config_architecture else "None"
        companion = f'Some("{model.companion_id}")' if model.companion_id else "None"
        assets.append(f'    ModelAsset {{ id: "{model.id}", repositories: &[{repositories}], required_files: &[{files}], config_model_type: {config_type}, config_architecture: {architecture}, companion_id: {companion} }},')
    sections = (
        "//! Generated model catalog shared by the Rust Host.\n"
        "//! Edit `src/whisper_subtitle/domain/models.py` and run the generator.",
        f'pub(super) const DEFAULT_MODEL_ID: &str = "{DEFAULT_MODEL_ID}";',
        _rust_array("SUPPORTED_MODEL_IDS", SUPPORTED_MODEL_IDS),
        _rust_array(
            "SECONDARY_RECOGNITION_MODEL_IDS",
            _ordered(SECONDARY_RECOGNITION_MODEL_IDS),
        ),
        _rust_array("TRANSLATION_MODEL_IDS", _ordered(TRANSLATION_MODEL_IDS)),
        _rust_array("QWEN_MODEL_IDS", [m.id for m in MODEL_DEFINITIONS if m.backend == "qwen3-asr"]),
        _rust_array("QWEN_PARAMETER_NAMES", sorted(QWEN_PARAMETER_NAMES)),
        _rust_array("QWEN_LANGUAGES", QWEN_LANGUAGES),
        "pub(super) struct ModelAsset { pub id: &'static str, pub repositories: &'static [&'static str], pub required_files: &'static [&'static str], pub config_model_type: Option<&'static str>, pub config_architecture: Option<&'static str>, pub companion_id: Option<&'static str> }",
        "pub(super) const MODEL_ASSETS: &[ModelAsset] = &[\n" + "\n".join(assets) + "\n];",
        "pub(super) const MODEL_CATALOG: &[(&str, &str, &[&str])] = &[\n"
        + "\n".join(entries)
        + "\n];",
    )
    return subprocess.run(["rustfmt", "--edition", "2024"], input="\n\n".join(sections) + "\n",
                          text=True, encoding="utf-8", capture_output=True, check=True).stdout


def _model_enums(value: Any) -> Iterable[list[str]]:
    if isinstance(value, dict):
        model_id = value.get("model_id")
        if isinstance(model_id, dict) and isinstance(model_id.get("enum"), list):
            yield model_id["enum"]
        for child in value.values():
            yield from _model_enums(child)
    elif isinstance(value, list):
        for child in value:
            yield from _model_enums(child)


def schema_errors() -> list[str]:
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    enums = list(_model_enums(schema))
    supported = list(SUPPORTED_MODEL_IDS)
    translation = list(_ordered(TRANSLATION_MODEL_IDS))
    if not enums:
        return ["Desktop IPC schema has no model_id enum"]
    errors = [
        f"Desktop IPC model_id enum #{index} differs from the Python catalog capabilities"
        for index, values in enumerate(enums, start=1)
        if tuple(values) not in {tuple(supported), tuple(translation), tuple(qwen_model_ids())}
    ]
    if supported not in enums:
        errors.append("Desktop IPC schema does not expose the complete model catalog")
    if translation not in enums:
        errors.append("Desktop IPC schema does not enforce translation model capabilities")
    if schema["$defs"].get("QwenModelParameters") != qwen_parameter_constraint():
        errors.append("Desktop IPC Qwen parameter capabilities are stale")
    return errors


def qwen_model_ids() -> list[str]:
    return [model.id for model in MODEL_DEFINITIONS if model.backend == "qwen3-asr"]


def qwen_parameter_constraint() -> dict[str, Any]:
    return {
        "if": {"required": ["model_id"], "properties": {"model_id": {"enum": qwen_model_ids()}}},
        "then": {"properties": {"profile": {"properties": {"overrides": {
            "propertyNames": {"enum": sorted(QWEN_PARAMETER_NAMES)},
            "properties": {"language": {"enum": [None, *QWEN_LANGUAGES]}},
        }}}}},
    }


def update_schema_constraint() -> None:
    raw = SCHEMA_PATH.read_text(encoding="utf-8")
    marker = '    "QwenModelParameters": '
    start = raw.index("{", raw.index(marker) + len(marker))
    _, length = json.JSONDecoder().raw_decode(raw[start:])
    replacement = json.dumps(qwen_parameter_constraint(), ensure_ascii=False, indent=2).replace("\n", "\n    ")
    SCHEMA_PATH.write_text(raw[:start] + replacement + raw[start + length:], encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if not args.check:
        update_schema_constraint()
    expected = {
        TYPESCRIPT_OUTPUT: render_typescript(),
        RUST_OUTPUT: render_rust(),
    }
    errors = schema_errors()
    if args.check:
        for path, content in expected.items():
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                errors.append(f"stale generated model catalog: {path}")
        if errors:
            print("\n".join(errors), file=sys.stderr)
            return 1
        return 0
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return 1
    for path, content in expected.items():
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"generated {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
