/* This file is generated by scripts/generate_model_catalog.py. */
/* Edit src/whisper_subtitle/domain/models.py instead. */

export const MODEL_IDS = ['tiny', 'base', 'small', 'medium', 'large-v3', 'large-v3-turbo'] as const;

export const DEFAULT_MODEL_ID = 'large-v3-turbo' as const;

export const CALIBRATED_MODEL_IDS = ['large-v3', 'large-v3-turbo'] as const;

export const SECONDARY_RECOGNITION_MODEL_IDS = ['large-v3', 'large-v3-turbo'] as const;

export const TRANSLATION_MODEL_IDS = ['tiny', 'base', 'small', 'medium', 'large-v3'] as const;

export const VISIBLE_MODEL_IDS = ['large-v3', 'large-v3-turbo'] as const;
