import type {
  DesktopBridge,
  DesktopEvent,
  HardwarePreference,
  HostStatus,
  InputOrigin,
  InputSource,
  LocalModelDescriptor,
  ModelId,
  PerformanceSample,
  OutputPathStatus,
  OutputPreview,
  TaskSnapshot,
  TranscriptionDraft,
  Unlisten,
} from '../contracts/desktop';
import { PERFORMANCE_POLL_INTERVAL_MS } from '../state/performanceWindow';

const SAMPLE_FILES: InputSource[] = [
  {
    id: 'source-lesson',
    path: 'C:\\Media\\课程目录\\P20-核心语法-整数类型.mp4',
    kind: 'file',
    origin: 'dialog',
    valid: true,
  },
  {
    id: 'source-interview',
    path: 'D:\\素材\\Product Interview 07.mkv',
    kind: 'file',
    origin: 'dialog',
    valid: true,
  },
];

const SAMPLE_DIRECTORY: InputSource = {
  id: 'source-folder',
  path: 'E:\\录音归档\\七月产品会议',
  kind: 'directory',
  origin: 'dialog',
  valid: true,
  mediaCount: 8,
  detail: '递归发现 8 个媒体文件',
};

export class MockDesktopBridge implements DesktopBridge {
  readonly mode = 'mock' as const;

  private readonly listeners = new Set<(event: DesktopEvent) => void>();
  private readonly taskTimers = new Map<string, ReturnType<typeof setInterval>>();
  private performanceTimer: ReturnType<typeof setInterval> | undefined;
  private taskSequence = 3;

  async selectFiles(): Promise<InputSource[]> {
    return structuredClone(SAMPLE_FILES);
  }

  async selectDirectory(): Promise<InputSource[]> {
    return [structuredClone(SAMPLE_DIRECTORY)];
  }

  async selectOutputDirectory(): Promise<string | null> {
    return 'D:\\字幕项目\\2026-07';
  }

  async inspectPaths(paths: string[], origin: InputOrigin): Promise<InputSource[]> {
    return paths.map((path, index) => ({
      id: `mock-inspected-${index}-${path}`,
      path,
      kind: 'file',
      origin,
      valid: true,
      mediaCount: 1,
    }));
  }

  async inspectOutputPaths(paths: string[]): Promise<OutputPathStatus[]> {
    return paths.map((path) => ({ path, exists: true }));
  }

  async revealOutput(path: string): Promise<void> {
    void path;
  }

  async readOutputPreview(path: string): Promise<OutputPreview> {
    return {
      path,
      content: 'This is a local output preview generated by the mock desktop bridge.\n',
      truncated: false,
    };
  }

  async copyWorkerLogs(content: string): Promise<void> {
    void content;
  }

  async exportWorkerLogs(content: string): Promise<string | null> {
    void content;
    return 'C:\\Users\\Mock\\Desktop\\WhisperSubtitle-WorkerLog-20260722-020000.txt';
  }

  async getHostStatus(): Promise<HostStatus> {
    return {
      state: 'ready',
      pid: 4242,
      launchKind: 'mock',
      error: null,
    };
  }

  async restartWorker(): Promise<HostStatus> {
    return this.getHostStatus();
  }

  async listLocalModels(): Promise<LocalModelDescriptor[]> {
    const installed = new Set<ModelId>(['medium', 'large-v3-turbo']);
    const labels: Record<ModelId, string> = {
      tiny: 'Tiny',
      base: 'Base',
      small: 'Small',
      medium: 'Medium',
      'large-v3': 'Large V3',
      'large-v3-turbo': 'Large V3 Turbo',
    };
    return (Object.keys(labels) as ModelId[]).map((id) => ({
      id,
      label: labels[id],
      installed: installed.has(id),
      path: installed.has(id) ? `D:\\WhisperSubtitle\\models\\${id}` : null,
      sizeBytes: installed.has(id) ? (id === 'medium' ? 1_532_000_000 : 1_620_000_000) : null,
      detail: installed.has(id) ? '本地模型完整，可离线加载' : `请放入 models\\${id}`,
    }));
  }

  async openModelDirectory(): Promise<string> {
    return 'D:\\WhisperSubtitle\\models';
  }

  async loadModel(modelId: ModelId, hardware?: HardwarePreference): Promise<void> {
    const preference = hardware ?? {
      mode: 'auto' as const,
      gpuDeviceIndex: 0,
      cudaComputeType: 'float16' as const,
      cpuComputeType: 'int8' as const,
      cpuThreads: 4,
    };
    const device = preference.mode === 'cpu' ? 'cpu' : 'cuda';
    this.emit({
      type: 'model.status',
      model: {
        state: 'loading',
        modelId,
        device: null,
        computeType: null,
        deviceIndex: null,
        cpuThreads: null,
      },
    });
    this.emit({
      type: 'model.status',
      model: {
        state: 'ready',
        modelId,
        device,
        computeType: device === 'cuda' ? preference.cudaComputeType : preference.cpuComputeType,
        deviceIndex: device === 'cuda' ? preference.gpuDeviceIndex : 0,
        cpuThreads: device === 'cpu' ? preference.cpuThreads : 0,
      },
    });
  }

  async startTranscription(draft: TranscriptionDraft): Promise<{ taskId: string }> {
    const taskId = `mock-task-${this.taskSequence++}`;
    const task: TaskSnapshot = {
      id: taskId,
      title: this.createTaskTitle(draft.inputs),
      sourceCount: draft.inputs.reduce((total, input) => total + (input.mediaCount ?? 1), 0),
      presetId: draft.basePresetId,
      modelId: draft.modelId,
      isCustom: Object.keys(draft.overrides).length > 0,
      status: 'queued',
      progress: 0,
      stage: '等待本地 GPU',
      elapsed: '00:00',
      createdAt: new Date().toISOString(),
      draft: structuredClone(draft),
      hardware: {
        device: draft.hardware.mode === 'cpu' ? 'cpu' : 'cuda',
        deviceIndex: draft.hardware.mode === 'cpu' ? 0 : draft.hardware.gpuDeviceIndex,
        computeType:
          draft.hardware.mode === 'cpu'
            ? draft.hardware.cpuComputeType
            : draft.hardware.cudaComputeType,
        cpuThreads: draft.hardware.mode === 'cpu' ? draft.hardware.cpuThreads : 0,
      },
    };

    this.emit({ type: 'task.queued', task });
    let progress = 0;
    const startedAt = Date.now();
    const timer = setInterval(() => {
      progress = Math.min(100, progress + 4 + Math.round(Math.random() * 7));
      const seconds = Math.floor((Date.now() - startedAt) / 1000);
      const elapsed = `00:${seconds.toString().padStart(2, '0')}`;
      if (progress >= 100) {
        clearInterval(timer);
        this.taskTimers.delete(taskId);
        this.emit({
          type: 'task.completed',
          taskId,
          elapsed,
          outputs: [
            draft.profileMode === 'subtitle'
              ? 'D:\\Mock\\subtitle.srt'
              : 'D:\\Mock\\transcript.txt',
          ],
        });
        return;
      }
      this.emit({
        type: 'task.progress',
        taskId,
        progress,
        stage: progress < 18 ? '准备模型' : progress < 88 ? 'GPU 转录中' : '整理输出',
        elapsed,
      });
    }, 650);
    this.taskTimers.set(taskId, timer);
    return { taskId };
  }

  async cancelTask(taskId: string): Promise<void> {
    const timer = this.taskTimers.get(taskId);
    if (timer !== undefined) {
      clearInterval(timer);
      this.taskTimers.delete(taskId);
    }
    this.emit({ type: 'task.cancelled', taskId });
  }

  subscribe(listener: (event: DesktopEvent) => void): Unlisten {
    this.listeners.add(listener);
    queueMicrotask(() =>
      listener({
        type: 'worker.environment',
        environment: {
          available: true,
          errors: [],
          python: '3.13.5',
          platform: 'Windows mock',
          hardware: {
            cpuName: 'Intel(R) Core(TM) i7-14700KF',
            cpuPhysicalCores: 20,
            cpuLogicalCores: 28,
            cpuComputeTypes: ['int8', 'float32'],
            gpus: [
              {
                index: 0,
                name: 'NVIDIA GeForce RTX 5070 Ti',
                computeTypes: ['float16', 'int8_float16', 'float32'],
              },
            ],
          },
        },
      }),
    );
    if (this.performanceTimer === undefined) {
      this.performanceTimer = setInterval(
        () => this.emitPerformance(),
        PERFORMANCE_POLL_INTERVAL_MS,
      );
    }
    return () => {
      this.listeners.delete(listener);
      if (this.listeners.size === 0 && this.performanceTimer !== undefined) {
        clearInterval(this.performanceTimer);
        this.performanceTimer = undefined;
      }
    };
  }

  dispose(): void {
    this.taskTimers.forEach((timer) => clearInterval(timer));
    this.taskTimers.clear();
    if (this.performanceTimer !== undefined) clearInterval(this.performanceTimer);
    this.performanceTimer = undefined;
    this.listeners.clear();
  }

  private createTaskTitle(inputs: InputSource[]): string {
    if (inputs.length !== 1) return `${inputs.length} 个输入来源`;
    const path = inputs[0]?.path ?? '未命名任务';
    return path.split(/[/\\]/).at(-1) ?? path;
  }

  private emit(event: DesktopEvent): void {
    this.listeners.forEach((listener) => listener(event));
  }

  private emitPerformance(): void {
    const sample: PerformanceSample = {
      source: 'mock',
      gpu: 68 + Math.round(Math.random() * 14),
      vramUsed: 7.8 + Math.random() * 0.5,
      vramTotal: 16,
      cpu: 20 + Math.round(Math.random() * 11),
      memory: 42 + Math.round(Math.random() * 5),
      speed: 4.5 + Math.random() * 0.8,
      memoryUsed: 13.4,
      memoryTotal: 32,
      memoryAvailable: 18.6,
      swapUsed: 0.2,
      swapTotal: 32,
      workerRss: 0.42,
      workerThreadCount: 18,
      workerHandleCount: 264,
      cpuName: 'Intel(R) Core(TM) i7-14700KF',
      cpuFrequencyMhz: 5200,
      cpuPhysicalCores: 20,
      cpuLogicalCores: 28,
      systemProcessCount: 278,
      systemUptimeSeconds: 16315,
      gpuName: 'RTX 5070 Ti',
      gpuMemoryController: 34,
      gpuTemperature: 44,
      gpuClockMhz: 2670,
      gpuMemoryClockMhz: 14001,
      gpuPowerWatts: 126,
      gpuPowerLimitWatts: 300,
      gpuFanPercent: 42,
      gpuDriverVersion: '610.62',
      gpuPerformanceState: 'P2',
      timestamp: Date.now(),
    };
    this.emit({ type: 'performance.sample', sample });
  }
}
