import type {
  DesktopBridge,
  DesktopEvent,
  HostStatus,
  InputOrigin,
  InputSource,
  PerformanceSample,
  OutputPreview,
  TaskSnapshot,
  TranscriptionDraft,
  Unlisten,
} from '../contracts/desktop';

const SAMPLE_FILES: InputSource[] = [
  {
    id: 'source-lesson',
    path: 'C:\\Media\\课程目录\\P20-核心语法-整数类型.mp4',
    kind: 'file',
    origin: 'dialog',
    valid: true,
  },
  {
    id: 'source-interview',
    path: 'D:\\素材\\Product Interview 07.mkv',
    kind: 'file',
    origin: 'dialog',
    valid: true,
  },
];

const SAMPLE_DIRECTORY: InputSource = {
  id: 'source-folder',
  path: 'E:\\录音归档\\七月产品会议',
  kind: 'directory',
  origin: 'dialog',
  valid: true,
  detail: '预计发现 8 个媒体文件',
};

export class MockDesktopBridge implements DesktopBridge {
  readonly mode = 'mock' as const;

  private readonly listeners = new Set<(event: DesktopEvent) => void>();
  private readonly taskTimers = new Map<string, ReturnType<typeof setInterval>>();
  private performanceTimer: ReturnType<typeof setInterval> | undefined;
  private taskSequence = 3;

  async selectFiles(): Promise<InputSource[]> {
    return structuredClone(SAMPLE_FILES);
  }

  async selectDirectory(): Promise<InputSource[]> {
    return [structuredClone(SAMPLE_DIRECTORY)];
  }

  async selectOutputDirectory(): Promise<string | null> {
    return 'D:\\字幕项目\\2026-07';
  }

  async inspectPaths(paths: string[], origin: InputOrigin): Promise<InputSource[]> {
    return paths.map((path, index) => ({
      id: `mock-inspected-${index}-${path}`,
      path,
      kind: 'file',
      origin,
      valid: true,
    }));
  }

  async revealOutput(path: string): Promise<void> {
    void path;
  }

  async readOutputPreview(path: string): Promise<OutputPreview> {
    return {
      path,
      content: 'This is a local output preview generated by the mock desktop bridge.\n',
      truncated: false,
    };
  }

  async getHostStatus(): Promise<HostStatus> {
    return {
      state: 'ready',
      pid: 4242,
      launchKind: 'mock',
      error: null,
    };
  }

  async restartWorker(): Promise<HostStatus> {
    return this.getHostStatus();
  }

  async startTranscription(draft: TranscriptionDraft): Promise<{ taskId: string }> {
    const taskId = `mock-task-${this.taskSequence++}`;
    const task: TaskSnapshot = {
      id: taskId,
      title: this.createTaskTitle(draft.inputs),
      sourceCount: draft.inputs.length,
      presetId: draft.basePresetId,
      isCustom: Object.keys(draft.overrides).length > 0,
      status: 'queued',
      progress: 0,
      stage: '等待本地 GPU',
      elapsed: '00:00',
      createdAt: new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }),
    };

    this.emit({ type: 'task.queued', task });
    let progress = 0;
    const startedAt = Date.now();
    const timer = setInterval(() => {
      progress = Math.min(100, progress + 4 + Math.round(Math.random() * 7));
      const seconds = Math.floor((Date.now() - startedAt) / 1000);
      const elapsed = `00:${seconds.toString().padStart(2, '0')}`;
      if (progress >= 100) {
        clearInterval(timer);
        this.taskTimers.delete(taskId);
        this.emit({
          type: 'task.completed',
          taskId,
          elapsed,
          outputs: ['D:\\Mock\\transcript.txt'],
        });
        return;
      }
      this.emit({
        type: 'task.progress',
        taskId,
        progress,
        stage: progress < 18 ? '准备模型' : progress < 88 ? 'GPU 转录中' : '整理输出',
        elapsed,
      });
    }, 650);
    this.taskTimers.set(taskId, timer);
    return { taskId };
  }

  async cancelTask(taskId: string): Promise<void> {
    const timer = this.taskTimers.get(taskId);
    if (timer !== undefined) {
      clearInterval(timer);
      this.taskTimers.delete(taskId);
    }
    this.emit({ type: 'task.cancelled', taskId });
  }

  subscribe(listener: (event: DesktopEvent) => void): Unlisten {
    this.listeners.add(listener);
    if (this.performanceTimer === undefined) {
      this.performanceTimer = setInterval(() => this.emitPerformance(), 1800);
    }
    return () => {
      this.listeners.delete(listener);
      if (this.listeners.size === 0 && this.performanceTimer !== undefined) {
        clearInterval(this.performanceTimer);
        this.performanceTimer = undefined;
      }
    };
  }

  dispose(): void {
    this.taskTimers.forEach((timer) => clearInterval(timer));
    this.taskTimers.clear();
    if (this.performanceTimer !== undefined) clearInterval(this.performanceTimer);
    this.performanceTimer = undefined;
    this.listeners.clear();
  }

  private createTaskTitle(inputs: InputSource[]): string {
    if (inputs.length !== 1) return `${inputs.length} 个输入来源`;
    const path = inputs[0]?.path ?? '未命名任务';
    return path.split(/[/\\]/).at(-1) ?? path;
  }

  private emit(event: DesktopEvent): void {
    this.listeners.forEach((listener) => listener(event));
  }

  private emitPerformance(): void {
    const sample: PerformanceSample = {
      source: 'mock',
      gpu: 68 + Math.round(Math.random() * 14),
      vramUsed: 7.8 + Math.random() * 0.5,
      vramTotal: 16,
      cpu: 20 + Math.round(Math.random() * 11),
      memory: 42 + Math.round(Math.random() * 5),
      speed: 4.5 + Math.random() * 0.8,
      memoryUsed: 13.4,
      memoryTotal: 32,
      gpuName: 'RTX 5070 Ti',
      timestamp: Date.now(),
    };
    this.emit({ type: 'performance.sample', sample });
  }
}
