"""Generate the UI preset projection from the Python domain registry.

The Python domain registry remains the only editable source for transcription
defaults and model calibration. The generated TypeScript file is a build-time
projection for the React parameter editor; it is never edited by hand.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from whisper_subtitle.domain.presets import (  # noqa: E402
    MODEL_CALIBRATED_IDS,
    PRESETS,
    derive_preset,
)
from whisper_subtitle.paths import SUPPORTED_MODEL_IDS  # noqa: E402


OUTPUT_PATH = PROJECT_ROOT / "apps" / "web" / "src" / "data" / "presetCatalog.generated.ts"
MODEL_IDS = tuple(SUPPORTED_MODEL_IDS)
UI_PARAMETER_KEYS = (
    "task",
    "beam_size",
    "best_of",
    "patience",
    "length_penalty",
    "temperature",
    "repetition_penalty",
    "no_repeat_ngram_size",
    "compression_ratio_threshold",
    "log_prob_threshold",
    "no_speech_threshold",
    "condition_on_previous_text",
    "prompt_reset_on_temperature",
    "initial_prompt",
    "hotwords",
    "min_silence_duration_ms",
)


def ui_parameters(preset: Any, model_id: str) -> dict[str, Any]:
    """Return the UI-shaped editable projection for one model/preset pair."""

    base = preset.transcription_options()
    effective = derive_preset(preset.id, {}, model_id=model_id).transcription_options()
    values: dict[str, Any] = {}
    for key in UI_PARAMETER_KEYS:
        if key in {"initial_prompt", "hotwords"}:
            # The Worker owns canonical decoder prompts. The UI only edits an
            # optional override, so its default must stay empty.
            values[key] = ""
        elif key == "temperature":
            # Model fallback ladders are runtime behavior, not a fixed numeric
            # editor value. Keep the existing UI's model mode at the base value.
            values[key] = base[key]
        elif key == "min_silence_duration_ms":
            values[key] = effective["vad_parameters"][key]
        else:
            values[key] = effective[key]
    return values


def build_catalog() -> tuple[dict[str, dict[str, dict[str, Any]]], dict[str, Any]]:
    parameters: dict[str, dict[str, dict[str, Any]]] = {}
    for preset in PRESETS:
        parameters[preset.id] = {
            model_id: ui_parameters(preset, model_id) for model_id in MODEL_IDS
        }

    profiles: dict[str, Any] = {}
    for model_id in MODEL_IDS:
        if model_id not in MODEL_CALIBRATED_IDS:
            profiles[model_id] = {"temperatureFallbackMax": None}
            continue
        sample = derive_preset(PRESETS[0].id, {}, model_id=model_id).transcription_options()
        profiles[model_id] = {
            "temperatureFallbackMax": max(sample["temperature"]),
        }
    return parameters, profiles


def render() -> str:
    parameters, profiles = build_catalog()
    parameter_json = json.dumps(parameters, ensure_ascii=False, indent=2)
    profile_json = json.dumps(profiles, ensure_ascii=False, indent=2)
    source = (
        "/* This file is generated by scripts/generate_preset_catalog.py. */\n"
        "/* Edit src/whisper_subtitle/domain/presets.py instead. */\n\n"
        "import type { EditableParameters, ModelId, PresetId } from '../contracts/desktop';\n\n"
        "export const GENERATED_PRESET_PARAMETERS = "
        f"{parameter_json} as const satisfies Record<PresetId, Record<ModelId, EditableParameters>>;\n\n"
        "export const GENERATED_MODEL_PROFILES = "
        f"{profile_json} as const satisfies Record<\n"
        "  ModelId,\n"
        "  { temperatureFallbackMax: number | null }\n"
        ">;\n"
    )
    corepack = shutil.which("corepack") or shutil.which("corepack.cmd")
    if corepack is None:
        raise RuntimeError("corepack is required to format the generated TypeScript catalog")
    formatted = subprocess.run(
        [corepack, "pnpm", "exec", "prettier", "--parser", "typescript"],
        cwd=PROJECT_ROOT,
        input=source,
        capture_output=True,
        check=True,
        text=True,
    )
    return formatted.stdout


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the generated file is stale")
    args = parser.parse_args()
    expected = render()
    current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else None
    if args.check:
        if current != expected:
            print(f"stale generated preset catalog: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8", newline="\n")
    print(f"generated {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
